{% set name = "reals" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reals-{{ version }}.tar.gz
  sha256: e435b8bd59454607ebca4b5b3032ca461e8c86e09c57ece68998fa96123f58a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools >=42
  run:
    - python >=3.10

test:
  imports:
    - reals
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rubenvannieuwpoort/reals
  summary: A lightweight python3 library for arithmetic with real numbers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
