{% set python_min = "3.10" %}
{% set name = "reals" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reals-{{ version }}.tar.gz
  sha256: a981642415a2ebb676a95abb34683af58105511d3d27b8445d462d5f878522f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42
  run:
    - python >={{ python_min }}

test:
  imports:
    - reals
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rubenvannieuwpoort/reals
  summary: A lightweight python3 library for arithmetic with real numbers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
